project:
     type: website
     output-dir: docs
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
website:
  title: "Generative AI For Everyone Cheatsheet"
  site-url: https://yourusername.github.io/your-repo-name/




